# standard jekyll configuration

title_en: "Jekyll variant - Working examples - Web Experience Toolkit&#160;(WET)"
title_fr: "Variant pour Jekyll - Exemples pratiques - Boîte à outils de l'expérience Web&#160;(BOEW)"
description_en: "Jekyll variant for the Web Experience Toolkit (WET)."
description_fr: "Variant pour Jekyll pour la Boîte à outils de l'expérience Web (BOEW)."
languages: true
search: false
subsite: false
site_menu: true
breadcrumb: true
content_editable: true
content_revision_history: true
content_questions_comments: true
date_modified: false
secondary_menu: false
secondary_menu_include: null
url: "http://wet-boew.github.io/wet-boew-jekyll/"
repo_name: "wet-boew-jekyll"
branch: "master"

#global settings, no need to change these
root_url: "http://wet-boew.github.io/wet-boew-jekyll/"
org_name: "wet-boew"
prose_url: "http://prose.io"

# default build settings for running locally, no need to edit
pymgemnts: true
exclude: ['README.md']

